[build]
base = "caregiver-hub"
command = "npm install && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
VITE_FIREBASE_API_KEY = "${FIREBASE_API_KEY}"
VITE_FIREBASE_AUTH_DOMAIN = "${FIREBASE_AUTH_DOMAIN}"
VITE_FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
VITE_FIREBASE_STORAGE_BUCKET = "${VITE_FIREBASE_STORAGE_BUCKET}"
VITE_FIREBASE_MESSAGING_SENDER_ID = "${VITE_FIREBASE_MESSAGING_SENDER_ID}"
VITE_FIREBASE_APP_ID = "${VITE_FIREBASE_APP_ID}"
VITE_FIREBASE_MEASUREMENT_ID = "${VITE_FIREBASE_MEASUREMENT_ID}"
VITE_VAPID_KEY = "${VITE_VAPID_KEY}"
BACKEND_URL = "${BACKEND_URL}"
VITE_FRONTEND_URL = "https://caregiverhub.netlify.app"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
