[build]
base = "caregiver-hub"
command = "npm install && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

VITE_FIREBASE_API_KEY = "AIzaSyAxh0tIjlxGm1CCtmlhwCyagYQ4MNbnDdo"
VITE_FIREBASE_AUTH_DOMAIN = "caregiver-coordination-hub.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "caregiver-coordination-hub"
VITE_FIREBASE_STORAGE_BUCKET = "caregiver-coordination-hub.appspot.com"
VITE_FIREBASE_MESSAGING_SENDER_ID = "450043180225"
VITE_FIREBASE_APP_ID = "1:450043180225:web:6259141b059625484236fe"
VITE_FIREBASE_MEASUREMENT_ID = "G-YEXL6ZZ4DT"
VITE_VAPID_KEY = "your_vapid_key=BEqLpOxWvyqVZNeLGd7aZLBiTMK1dm9qWUxW0h1vt4KAtojw06WjUaEVIcqJ0q_HfVbNnG_IafTghViuLTin05Y"
BACKEND_URL = "https://us-central1-caregiver-coordination-hub.cloudfunctions.net"
VITE_FRONTEND_URL = "https://caregiverhub.netlify.app"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
